import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { gunzipSync } from "node:zlib";
import { scoreRawCalibrationPoint, type RawCalibrationPoint } from "../lib/replay/populationCalibration";
import type { FeedAwareAttentionThresholdStore } from "../lib/replay/feedAwareAttentionThresholds";
import type { AttentionSubWindow } from "../lib/replay/attentionThresholdTypes";
import { PRE_STREAM_REPLAY_DISCLOSURE, sha256, stableJson } from "../lib/replay/archive";

type T=[number,number,number,number,number,0|1,0|1|2,number,number,number,number,number|null,number|null,number,0|1,0|1,0|1];
interface Corpus{dates:string[];symbols:string[];feeds:{sip:T[]}}
function subWindow(minute:number):AttentionSubWindow{if(minute<420)return"premarket_early";if(minute<540)return"premarket_core";if(minute<570)return"premarket_final";if(minute<960)return"regular";if(minute<1080)return"after_hours_core";return"after_hours_late"}
function clock(at:number){return new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(at))}
const reports=resolve("data/replay/reports"),calibration=resolve("data/replay/calibration");
const digest=JSON.parse(readFileSync(resolve(reports,"phase-c-alert-digest.json"),"utf8"));
const corpus=JSON.parse(gunzipSync(readFileSync(resolve(calibration,"raw-features.json.gz"))).toString("utf8")) as Corpus;
const store=JSON.parse(readFileSync(resolve(reports,"attention-thresholds.json"),"utf8")) as FeedAwareAttentionThresholdStore;
const tupleByKey=new Map<string,T>();for(const t of corpus.feeds.sip)tupleByKey.set(`${corpus.dates[t[0]]}|${corpus.symbols[t[1]]}|${t[2]}`,t);
const rows:any[]=[];
for(const item of digest.sessions){const date=item.session.tradingDate;for(const event of item.alerts.filter((row:any)=>row.type==="NEW_IN_PLAY")){const identity=`NEW_IN_PLAY|${event.episodeId}`,logs=item.suppressions.filter((row:any)=>row.eventIdentity===identity).sort((a:any,b:any)=>a.at-b.at),qualifyingAt=logs[0]?.at??event.at,t=tupleByKey.get(`${date}|${event.symbol}|${qualifyingAt}`);if(!t)throw new Error(`Missing corpus tuple for ${date} ${event.symbol} ${qualifyingAt}`);const w=subWindow(t[3]),set=store.sets.sip[w],raw:RawCalibrationPoint={tradingDate:date,symbol:event.symbol,minuteOfDay:t[3],feedMode:"sip",subWindow:w,participationInput:t[4],participationInputKind:t[5]?"surprise_bits":"z",displacementZ:t[7],idiosyncrasyZ:t[8],limitedHistory:!!t[16]},score=scoreRawCalibrationPoint(raw,set.normalization),emissionCore=Math.sqrt(event.payload.axes.participation.normalized*event.payload.axes.displacement.normalized),enter=set.values.inPlayEnterCore;if(enter===null)throw new Error(`Missing IN PLAY threshold for ${w}`);rows.push({tradingDate:date,symbol:event.symbol,episodeId:event.episodeId,qualifyingAt,qualifyingTimeEt:clock(qualifyingAt),emissionAt:event.at,emissionTimeEt:clock(event.at),gapMinutes:(event.at-qualifyingAt)/60000,qualifyingCore:score.core,emissionCore,enterThreshold:enter,qualifyingGateMet:score.core>=enter,emissionGateMet:emissionCore>=enter,emissionAttention:event.payload.attentionScore,emissionFreshness:event.payload.freshness,delayingReasons:[...new Set(logs.map((row:any)=>row.reason))],suppressionCount:logs.length})}}
const artifact:any={schemaVersion:1,status:"diagnosis_before_fix",disclosure:PRE_STREAM_REPLAY_DISCLOSURE,mechanism:{classification:"a",entryTransitionRequired:true,leaseExpiryCanBypassEntryGate:false,detail:"The qualifying transition is correct. Suppressed NEW IN PLAY edges remain pending, but payload construction reads the later emission row instead of the qualifying row."},rows,summary:{alerts:rows.length,qualifyingGateFailures:rows.filter(r=>!r.qualifyingGateMet).length,emissionGateFailures:rows.filter(r=>!r.emissionGateMet).length,zeroGap:rows.filter(r=>r.gapMinutes===0).length,delayed:rows.filter(r=>r.gapMinutes>0).length,gapMinutes:{min:Math.min(...rows.map(r=>r.gapMinutes)),median:[...rows].sort((a,b)=>a.gapMinutes-b.gapMinutes)[Math.floor(rows.length/2)].gapMinutes,max:Math.max(...rows.map(r=>r.gapMinutes))},delayingReasons:Object.fromEntries([...new Set(rows.flatMap(r=>r.delayingReasons))].map(reason=>[reason,rows.filter(r=>r.delayingReasons.includes(reason)).length]))}};artifact.artifactHash=sha256(stableJson(artifact));writeFileSync(resolve(reports,"phase-c-new-in-play-diagnosis.json"),JSON.stringify(artifact,null,2)+"\n");const lines=["# Phase C NEW IN PLAY payload diagnosis — before fix","",`> ${PRE_STREAM_REPLAY_DISCLOSURE}`,"","> Diagnosis only. No event behavior was changed while producing this report.","",`Mechanism: **(a)**. ${artifact.mechanism.detail}`,"",`All ${rows.length} qualifying rows met their exact IN PLAY entry gate; ${artifact.summary.emissionGateFailures} emitted payloads did not. The cooling-timeout creation path did not bypass the state gate.`,"","| Date | Symbol | Qualifying ET | Emission ET | Gap min | Qualifying core | Emission core | Threshold | Delay reason |","|---|---|---:|---:|---:|---:|---:|---:|---|",...rows.map(r=>`| ${r.tradingDate} | ${r.symbol} | ${r.qualifyingTimeEt} | ${r.emissionTimeEt} | ${r.gapMinutes} | ${r.qualifyingCore.toFixed(3)} | ${r.emissionCore.toFixed(3)} | ${r.enterThreshold.toFixed(3)} | ${r.delayingReasons.join(", ")||"none"} |`),"",`Artifact: \`${artifact.artifactHash}\`.`];writeFileSync(resolve(reports,"phase-c-new-in-play-diagnosis.md"),lines.join("\n")+"\n");console.log(JSON.stringify({artifactHash:artifact.artifactHash,summary:artifact.summary,rows},null,2));