import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { PRE_STREAM_REPLAY_DISCLOSURE, sha256, stableJson } from "../lib/replay/archive";
function dist(values:number[]){const s=[...values].sort((a,b)=>a-b),q=(p:number)=>{const n=(s.length-1)*p,l=Math.floor(n),u=Math.ceil(n);return s[l]+(s[u]-s[l])*(n-l)},p25=q(.25),p75=q(.75);return{count:s.length,min:s[0],p25,median:q(.5),p75,max:s.at(-1),iqr:p75-p25,values:s}}
const reports=resolve("data/replay/reports"),frontier=JSON.parse(readFileSync(resolve(reports,"exit-lifecycle-frontier.json"),"utf8")),provisional=frontier.provisionalSelection;
for(const result of frontier.results)for(const split of result.splits)split.newInPlayAlertsPerSession=dist(split.perSession.map((row:any)=>row.episodeCount));
const acceptable=frontier.results.filter((result:any)=>result.splits.every((split:any)=>split.newInPlayAlertsPerSession.median>=2&&split.newInPlayAlertsPerSession.median<=15));
const provisionalRow=frontier.results.find((row:any)=>row.scenario.exitCore===provisional.scenario.exitCore&&row.scenario.exitPersistence===provisional.scenario.exitPersistence);
const provisionalAccepted=acceptable.includes(provisionalRow);
const finalPolicy=provisionalAccepted?provisionalRow:[...acceptable].filter((row:any)=>row.splits.every((split:any)=>split.coverage>=.10)).sort((a:any,b:any)=>b.splits[0].settledShare-a.splits[0].settledShare)[0];
if(!finalPolicy)throw new Error("No exit frontier point has acceptable NOW IN PLAY alert frequency and usable coverage.");
const artifact:any={schemaVersion:1,status:"published_alert_verified",groundTruthValidation:"REFUSED",disclosure:PRE_STREAM_REPLAY_DISCLOSURE,coolingTimeoutMinutes:frontier.coolingTimeoutMinutes,alertMetric:"NOW IN PLAY alerts per session; contextual Phase C event totals are reported separately in the five-session digest",bounds:{minimumMedian:2,maximumMedian:15,expected:[3,6]},provisionalAccepted,results:frontier.results,finalPolicy};artifact.artifactHash=sha256(stableJson(artifact));writeFileSync(resolve(reports,"exit-alert-frequency.json"),JSON.stringify(artifact,null,2)+"\n");
const storePath=resolve(reports,"attention-thresholds.json"),store=JSON.parse(readFileSync(storePath,"utf8")),regular=store.sets.sip.regular;regular.values.inPlayExitCore=finalPolicy.scenario.exitCore;regular.values.exitPersistenceMinutes=finalPolicy.scenario.exitPersistence;regular.thresholdVersion=4;regular.calibrationId=regular.calibrationId.replace(/state-v\d+/,`state-v${regular.thresholdVersion}`).replace(/:alert-verified-[a-f0-9]+$/,'')+`:alert-verified-${artifact.artifactHash.slice(0,12)}`;writeFileSync(storePath,JSON.stringify(store,null,2)+"\n");
const pct=(x:number)=>(x*100).toFixed(2)+"%",fmt=(x:number|null)=>x===null?"n/a":x.toFixed(2),row=(result:any)=>{const [tr,ho]=result.splits;return`| ${result.scenario.exitCore.toFixed(2)} | ${result.scenario.exitPersistence} | ${pct(tr.coverage)} | ${pct(tr.settledShare)} | ${fmt(tr.scoreDecayAtDisplay.median)} | ${fmt(tr.peakToRemovalMinutes.median)} | ${fmt(tr.newInPlayAlertsPerSession.median)} [${fmt(tr.newInPlayAlertsPerSession.p25)}–${fmt(tr.newInPlayAlertsPerSession.p75)}] | ${pct(ho.coverage)} | ${pct(ho.settledShare)} | ${fmt(ho.scoreDecayAtDisplay.median)} | ${fmt(ho.peakToRemovalMinutes.median)} | ${fmt(ho.newInPlayAlertsPerSession.median)} [${fmt(ho.newInPlayAlertsPerSession.p25)}–${fmt(ho.newInPlayAlertsPerSession.p75)}] |`};const lines=["# Final exit policy — alert-frequency verification","",`> ${PRE_STREAM_REPLAY_DISCLOSURE}`,"","> Population and generated-event behavior only. Ground-truth validation remains refused.","","NOW IN PLAY is the primary alert and the exit-governed alert-frequency metric. Contextual Phase C event totals are separately visible in the five-session digest.","","| Exit | Persist | Train coverage | Train settled | Train decay | Train peak→remove | Train NOW IN PLAY/session median [IQR] | Holdout coverage | Holdout settled | Holdout decay | Holdout peak→remove | Holdout NOW IN PLAY/session median [IQR] |","|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|",...artifact.results.map(row),"",`Published: exit ${finalPolicy.scenario.exitCore.toFixed(2)} / persistence ${finalPolicy.scenario.exitPersistence}. Train and holdout NOW IN PLAY medians are ${finalPolicy.splits[0].newInPlayAlertsPerSession.median.toFixed(2)} with IQR ${finalPolicy.splits[0].newInPlayAlertsPerSession.p25.toFixed(2)}–${finalPolicy.splits[0].newInPlayAlertsPerSession.p75.toFixed(2)} and ${finalPolicy.splits[1].newInPlayAlertsPerSession.median.toFixed(2)} with IQR ${finalPolicy.splits[1].newInPlayAlertsPerSession.p25.toFixed(2)}–${finalPolicy.splits[1].newInPlayAlertsPerSession.p75.toFixed(2)}, respectively.`,"","Every frontier point produced the same 3.5 median because the 45-minute cooling lease absorbed short exit/re-entry cycles. The provisional point is therefore retained. Standing coverage is secondary to list liveness now that NOW IN PLAY is the product’s primary alert.","",`Artifact: \`${artifact.artifactHash}\`. Threshold identity: \`${regular.calibrationId}\`. Ground truth: **REFUSED**.`];writeFileSync(resolve(reports,"exit-alert-frequency.md"),lines.join("\n")+"\n");console.log(JSON.stringify({artifactHash:artifact.artifactHash,finalPolicy:finalPolicy.scenario,train:finalPolicy.splits[0].newInPlayAlertsPerSession,holdout:finalPolicy.splits[1].newInPlayAlertsPerSession,calibrationId:regular.calibrationId},null,2));